global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'goapp'
    static_configs:
    - targets: ['goapp:5555']
  - job_name: 'pythonapp'
    static_configs:
    - targets: ['pythonapp:4444']
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8181']

