apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://localhost:9090
  basicAuth: false
  isDefault: true
  jsonData:
    timeInterval: "5s"
    httpMethod: "GET"
    httpHeaderName1: "Authorization"
  secureJsonData:
    httpHeaderValue1: ""
